name:                shrimp
version:             0.1.0.0
github:              "loreloc/shrimp"
license:             BSD3
author:              "Lorenzo Loconte"
maintainer:          "lorenzoloconte@outlook.it"
copyright:           "2020 Lorenzo Loconte"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Shrimp, a very nice imperative programming language written in Haskell

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  shrimp:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - shrimp

tests:
  shrimp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shrimp
